# Use a predefined Docker image to build and test the project.
image: $SKA_K8S_TOOLS_DOCKER_BUILDER_IMAGE

variables:
  GIT_SUBMODULE_STRATEGY: recursive # Ensures that git submodules are recursively checked out if any.

# Cache configuration to store build files between jobs to speed up consecutive pipelines.
cache:
  paths:
    - build

# Define the pipeline stages.
stages:
  - lint
  - test

include:
# Python packages build,lint, test and publish
- project: 'ska-telescope/templates-repository'
  file: 'gitlab-ci/includes/python-lint.gitlab-ci.yml'

k8s-test-tmc-with-csp:
  image: $SKA_K8S_TOOLS_BUILD_DEPLOY # Use specific Docker image for this job.
  stage: test
  tags:
    - ska-k8s # GitLab runner tag to ensure the job runs on specific runners.
  variables:
    TELESCOPE: 'SKA-mid'
    KUBE_NAMESPACE: 'integration-ska-mid-tmc-csp'
    MARK: 'tmc_csp'
    CSP_SIMULATION_ENABLED: 'false' # Ensure CSP simulation is disabled.
  script:
    - make k8s-test MARK=tmc_csp
  environment:
    name: test/csp$CI_COMMIT_REF_SLUG # Set environment name dynamically based on branch or commit.
    on_stop: stop-k8s-test-mid-with-csp # Specify stop job.
    auto_stop_in: 1 minute # Automatically stop environment after a minute.
  rules:
    - exists: 
        - Mid/tests/**/* # Only run if test files for Mid exist.

# Job to stop the test environment for TMC with CSP.
stop-k8s-test-mid-with-csp:
  image: $SKA_K8S_TOOLS_BUILD_DEPLOY
  stage: test
  when: manual # Manual job to stop the environment.
  tags:
    - ska-k8s
  variables:
    KUBE_NAMESPACE: 'integration-ska-mid-tmc-csp'
  script:
    - make k8s-test MARK=tmc_csp # Delete the test runner pod in the Kubernetes namespace.
  environment:
    name: test/csp$CI_COMMIT_REF_SLUG
    on_stop: stop-k8s-test-mid-with-csp
    auto_stop_in: 1 minute
    action: stop # Stop action triggers the deletion.

# Job to test TMC with SDP components.
k8s-test-tmc-with-sdp:
  image: $SKA_K8S_TOOLS_BUILD_DEPLOY
  stage: test
  tags:
    - ska-k8s
  variables:
    TELESCOPE: 'SKA-mid'
    PORT: "10000"
    KUBE_NAMESPACE: 'integration-ska-mid-tmc-sdp'
    # KUBE_NAMESPACE_SDP: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-sdp'
    SUBARRAY_COUNT: 2 # Set subarray count for testing.
    SDP_SIMULATION_ENABLED: 'false' # Disable SDP simulation.
    TARANTA_ENABLED: 'true'
    MARK: tmc_sdp
  script:
    - make k8s-test MARK=tmc_sdp
  environment:
    name: test/sdp$CI_COMMIT_REF_SLUG
    on_stop: stop-k8s-test-tmc-with-sdp
    auto_stop_in: 1 minute
  rules:
    - exists: 
        - Mid/tests/**/*

# Job to stop the test environment for TMC with SDP.
stop-k8s-test-tmc-with-sdp:
  image: $SKA_K8S_TOOLS_BUILD_DEPLOY
  stage: test
  when: manual
  tags:
    - ska-k8s
  variables:
    KUBE_NAMESPACE: 'integration-ska-mid-tmc-sdp'
    # KUBE_NAMESPACE_SDP: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-sdp'
    SDP_SIMULATION_ENABLED: 'false'
  script:
    - kubectl delete pod
  environment:
    name: test/sdp$CI_COMMIT_REF_SLUG
    on_stop: stop-k8s-test-tmc-with-sdp
    auto_stop_in: 1 minute
    action: stop

# Job to test Dish-LMC with Kubernetes.
k8s-test-dish-lmc:
  image: $SKA_K8S_TOOLS_BUILD_DEPLOY
  stage: test
  tags:
    - ska-k8s
  variables:
    DISH_SIMULATION_ENABLED: "false"
    SUBARRAY_COUNT: 2
    DISH_TANGO_HOST: "tango-databaseds"
    PORT: "10000"
    DISH_INDEX_1: "001"
    DISH_INDEX_36: "036"
    DISH_INDEX_63: "063"
    DISH_INDEX_100: "100"
    DISH_NAMESPACE_1: "integration-ska-mid-tmc-dish01"
    DISH_NAMESPACE_2: "integration-ska-mid-tmc-dish36"
    DISH_NAMESPACE_3: "integration-ska-mid-tmc-dish63"
    DISH_NAMESPACE_4: "integration-ska-mid-tmc-dish100"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-dish-lmc-test"
    DISH_LMC_SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-dish-lmc-test"
  script:
    - make k8s-test MARK=tmc_dish
  environment:
    name: test/dish$CI_COMMIT_REF_SLUG
    on_stop: stop-k8s-test-dish-lmc
  rules:
    - exists: 
        - Mid/tests/**/*

# Job to stop the test environment for Dish-LMC.
stop-k8s-test-dish-lmc:
  image: $SKA_K8S_TOOLS_BUILD_DEPLOY
  stage: test
  when: manual
  tags:
    - ska-k8s
  variables:
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-dish-lmc-test"
  script:
    - make k8s-test MARK=tmc_dish
  environment:
    name: test/dish$CI_COMMIT_REF_SLUG
    on_stop: stop-k8s-test-dish-lmc
    auto_stop_in: 1 minute
    action: stop

# # Job to test TMC with CSP for the SKA-low telescope.
# k8s-test-tmc-low-with-csp:
#   image: $SKA_K8S_TOOLS_BUILD_DEPLOY
#   stage: test
#   tags:
#     - ska-k8s
#   variables:
#     TELESCOPE: 'SKA-low'
#     KUBE_NAMESPACE: 'integration-ska-low-tmc-csp'
#     KUBE_NAMESPACE_CSP: 'integration-ska-tmc-low-csp'
#     MARK: 'tmc_csp'
#     COUNT: 1
#     CSP_SIMULATION_ENABLED: 'false'
#   script:
#     - make k8s-test MARK=tmc_cso_low
#   environment:
#     name: test/$CI_COMMIT_REF_SLUG
#     on_stop: stop-k8s-test-low-with-csp
#     auto_stop_in: 1 minute
#   rules:
#     - exists: 
#         - Low/tests/**/*

# # Job to stop the test environment for TMC with CSP (SKA-low).
# stop-k8s-test-low-with-csp:
#   image: $SKA_K8S_TOOLS_BUILD_DEPLOY
#   stage: test
#   when: manual
#   tags:
#     - ska-k8s
#   variables:
#     KUBE_NAMESPACE: 'integration-ska-low-tmc-csp'
#   script:
#     - kubectl delete pod test-runner-test -n $KUBE_NAMESPACE
#   environment:
#     name: test/$CI_COMMIT_REF_SLUG
#     on_stop: stop-k8s-test-low-with-csp
#     auto_stop_in: 1 minute
#     action: stop

# # Job to test TMC with SDP for the SKA-low telescope.
# k8s-test-tmc-low-with-sdp:
#   image: $SKA_K8S_TOOLS_BUILD_DEPLOY
#   stage: test
#   tags:
#     - ska-k8s
#   variables:
#     TELESCOPE: 'SKA-low'
#     PORT: "10000"
#     KUBE_NAMESPACE: 'integration-ska-low-tmc-sdp'
#     KUBE_NAMESPACE_SDP: 'integration-ska-tmc-low-sdp'
#     SDP_SIMULATION_ENABLED: 'false'
#     TARANTA_ENABLED: 'true'
#     MARK: tmc_sdp
#   script:
#     - make k8s-test MARK=tmc_sdp_low
#   environment:
#     name: test/$CI_COMMIT_REF_SLUG
#     on_stop: stop-k8s-test-tmc-low-with-sdp
#     auto_stop_in: 1 minute
#   rules:
#     - exists: 
#         - Low/tests/**/*

# # Job to stop the test environment for TMC with SDP (SKA-low).
# stop-k8s-test-tmc-low-with-sdp:
#   image: $SKA_K8S_TOOLS_BUILD_DEPLOY
#   stage: test
#   when: manual
#   tags:
#     - ska-k8s
#   variables:
#     KUBE_NAMESPACE: 'integration-ska-low-tmc-sdp'
#     KUBE_NAMESPACE_SDP: 'integration-ska-tmc-low-sdp'
#     SDP_SIMULATION_ENABLED: 'false'
#   script:
#     - make k8s-test MARK=tmc_sdp_low
#   environment:
#     name: test/$CI_COMMIT_REF_SLUG
#     on_stop: stop-k8s-test-tmc-low-with-sdp
#     auto_stop_in: 1 minute
#     action: stop
    
# k8s-test-tmc-low-with-mccs:
#   image: $SKA_K8S_TOOLS_BUILD_DEPLOY
#   stage: test
#   tags:
#     - ska-k8s
#   variables:
#     TELESCOPE: 'SKA-low'
#     PORT: "10000"
#     KUBE_NAMESPACE: 'integration-ska-low-tmc-mccs'
#     KUBE_NAMESPACE_MCCS: 'integration-ska-tmc-low-mccs'
#     MCCS_SIMULATION_ENABLED: 'false'
#   script:
#     - make k8s-test MARK=tmc_mccs
#   environment:
#     name: test/$CI_COMMIT_REF_SLUG
#     on_stop: stop-k8s-test-tmc-low-with-mccs

# stop-k8s-test-tmc-low-with-mccs:
#   name: test/$CI_COMMIT_REF_SLUG
#   on_stop: stop-k8s-test-tmc-low-with-mccs
#   auto_stop_in: 1 minute
#   action: stop