# Use a predefined Docker image to build and test the project.
image: $SKA_K8S_TOOLS_DOCKER_BUILDER_IMAGE

variables:
  GIT_SUBMODULE_STRATEGY: recursive # Ensures that git submodules are recursively checked out if any.

# Cache configuration to store build files between jobs to speed up consecutive pipelines.
cache:
  paths:
    - build

stages:
  - lint
  - build
  - test
  - integration
  - publish
  - staging
  - pages
  - scan
  - lifecycle

include:
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python-lint.gitlab-ci.yml'

  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/release.gitlab-ci.yml'

  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/helm-chart.gitlab-ci.yml'

  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs-pages.gitlab-ci.yml'

  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs.gitlab-ci.yml'

  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/k8s.gitlab-ci.yml'

  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/deploy.integration.gitlab-ci.yml'

  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/deploy.staging.gitlab-ci.yml"

  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'


k8s-test-low:
  image: $SKA_K8S_TOOLS_BUILD_DEPLOY
  stage: test
  tags:
    - ska-k8s
  variables:
    CONFIG: "Low"
    TELESCOPE: 'SKA-low'
    KUBE_NAMESPACE: 'ci-dev-ska-low-integration'
    MARK: 'system_level_test'
    CSP_SIMULATION_ENABLED: 'false'
    SDP_SIMULATION_ENABLED: 'false'
    MCCS_SIMULATION_ENABLED: 'false'
  script:
    - make k8s-test MARK='system_level_test'
  after_script:
    - pip3 install -q -U ska-ser-xray
    - XRAY_TEST_RESULT_FILE="build/cucumber.json" make xray-publish
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_ID-low"
    paths:
      - "build/"
    reports:
      junit: build/report.xml
    when: always
  environment:
    name: test/low-$CI_COMMIT_REF_SLUG
    on_stop: stop-k8s-test-low 
    auto_stop_in: 1 minute

# Job to stop the test environment for TMC with CSP.
stop-k8s-test-low:
  image: $SKA_K8S_TOOLS_BUILD_DEPLOY
  stage: test
  when: manual 
  tags:
    - ska-k8s
  variables:
    KUBE_NAMESPACE: 'ci-dev-ska-low-integration'
  script:
    - kubectl delete pod test-runner-test -n ${KUBE_NAMESPACE}
  environment:
    name: test/low-$CI_COMMIT_REF_SLUG
    on_stop: stop-k8s-test-low-all
    auto_stop_in: 1 minute
    action: stop 
