k8s-test-tmc-with-sdp:
  extends:
    - k8s-test
  tags:
    - ska-k8s
  variables:
    TELESCOPE: 'SKA-mid'
    PORT: "10000"
    KUBE_NAMESPACE: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-tmc-sdp'
    KUBE_NAMESPACE_SDP: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-sdp'
    SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-tmc-sdp"
    SUBARRAY_COUNT: 2
    SDP_SIMULATION_ENABLED: 'false'
    TARANTA_ENABLED: 'true'
  script:
    - make cred SERVICE_ACCOUNT=$SERVICE_ACCOUNT
    - '[ -f .make/k8s.mk ] || (echo "File k8s.mk not included in Makefile; exit 1")'
    - 'make help | grep k8s-test'
    - make k8s-install-chart SDP_PROCCONTROL_REPLICAS=0
    - chmod u=rwx,go=rx tests/scripts/sdp_data_copy.sh
    - ${PWD}/tests/scripts/sdp_data_copy.sh create_pod
    - make k8s-wait
    - make k8s-test MARK='tmc_sdp_unhappy'
    - make k8s-install-chart SDP_PROCCONTROL_REPLICAS=1
    - make k8s-wait
    - make k8s-test MARK='tmc_sdp'
  after_script:
    - ls -al
    - ls -al build
    - ls -al tests
    - pip3 install -U ska-ser-xray
    - XRAY_TEST_RESULT_FILE="build/cucumber.json" make xray-publish

  environment:
    name: test/$CI_COMMIT_REF_SLUG
    on_stop: stop-k8s-test-tmc-with-sdp
    auto_stop_in: 1 minute


stop-k8s-test-tmc-with-sdp:
  extends:
    - stop-k8s-test
  variables:
    KUBE_NAMESPACE: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-tmc-sdp'
    SDP_SIMULATION_ENABLED: 'false'
    KUBE_NAMESPACE_SDP: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-sdp' 
  script:
    - ${PWD}/tests/scripts/sdp_data_copy.sh delete_pod
    - make k8s-uninstall-chart
    - kubectl -n $KUBE_NAMESPACE delete pods,svc,daemonsets,deployments,replicasets,statefulsets,cronjobs,jobs,ingresses,configmaps --all
    - make k8s-delete-namespace
