k8s-test-mid-with-csp:
  extends:
    - k8s-test
  variables:
    TELESCOPE: 'SKA-mid'
    KUBE_NAMESPACE: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-csp-mid'
    SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-csp-mid"
    MARK: 'tmc_csp'
    CSP_SIMULATION_ENABLED: 'false'
  environment:
    name: test/$CI_COMMIT_REF_SLUG
    on_stop: stop-k8s-test-mid-with-csp
    auto_stop_in: 1 minute


stop-k8s-test-mid-with-csp:
  extends:
    - stop-k8s-test
  variables:
    KUBE_NAMESPACE: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-csp-mid'
  script:
    - make k8s-uninstall-chart
    - kubectl -n $KUBE_NAMESPACE delete pods,svc,daemonsets,deployments,replicasets,statefulsets,cronjobs,jobs,ingresses,configmaps --all
    - make k8s-delete-namespace