
dish-lmc-dish001:
  extends:
    - k8s-test
  stage: test
  tags:
    - ska-k8s
  variables:
    DISH_INDEX: "001"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-dish-lmc-$DISH_INDEX"
    DISH_LMC_SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-dish-lmc-$DISH_INDEX"
    DISH_HELM_RELEASE: "4.1.0"
    K8S_DISH_LMC_CHART: "ska-dish-lmc"
  before_script:
    - make cred SERVICE_ACCOUNT=$DISH_LMC_SERVICE_ACCOUNT
  script:
    - make k8s-install-chart-car KUBE_NAMESPACE=$KUBE_NAMESPACE K8S_CHART_PARAMS='-f charts/dish_lmc_values.yml
      --set "global.dishes={$(DISH_INDEX)}" --version=4.1.0
      --set global.cluster_domain=$(CLUSTER_DOMAIN)'
      HELM_RELEASE=$DISH_HELM_RELEASE K8S_CHART=$K8S_DISH_LMC_CHART
    - make k8s-wait
  environment:
    name: test/$CI_COMMIT_REF_SLUG
    on_stop: stop-k8s-dish-lmc-001
    action: stop
  allow_failure: true


dish-lmc-dish036:
  extends:
    - k8s-test
  extends:
    - dish-lmc-dish001
  variables:
    DISH_INDEX: "036"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-dish-lmc-$DISH_INDEX"
    DISH_LMC_SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-dish-lmc-$DISH_INDEX"
    DISH_HELM_RELEASE: "4.1.0"
    K8S_DISH_LMC_CHART: "ska-dish-lmc"
  environment:
    name: test/$CI_COMMIT_REF_SLUG
    on_stop: stop-k8s-dish-lmc-036
    action: stop

dish-lmc-dish063:
  extends:
    - k8s-test
  extends:
    - dish-lmc-dish001
  variables:
    DISH_INDEX: "063"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-dish-lmc-$DISH_INDEX"
    DISH_LMC_SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-dish-lmc-$DISH_INDEX"
    DISH_HELM_RELEASE: "4.1.0"
    K8S_DISH_LMC_CHART: "ska-dish-lmc"
  environment:
    name: test/$CI_COMMIT_REF_SLUG
    on_stop: stop-k8s-dish-lmc-063
    action: stop

dish-lmc-dish100:
  extends:
    - k8s-test
  extends:
    - dish-lmc-dish001
  variables:
    DISH_INDEX: "100"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-dish-lmc-$DISH_INDEX"
    DISH_LMC_SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-dish-lmc-$DISH_INDEX"
    DISH_HELM_RELEASE: "4.1.0"
    K8S_DISH_LMC_CHART: "ska-dish-lmc"
    TARANTA_ENABLED: "true"
  environment:
    name: test/$CI_COMMIT_REF_SLUG
    on_stop: stop-k8s-dish-lmc-100
    action: stop



stop-k8s-dish-lmc-001:
  stage: test
  extends:
    - stop-k8s-test
  variables:
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-dish-lmc-001"
    DISH_HELM_RELEASE: "4.1.0"
    K8S_DISH_LMC_CHART: "ska-dish-lmc"
  script:
    - make k8s-do-uninstall-chart KUBE_NAMESPACE=$KUBE_NAMESPACE HELM_RELEASE=$DISH_HELM_RELEASE K8S_CHART=$K8S_DISH_LMC_CHART
    - kubectl -n $KUBE_NAMESPACE delete pods,svc,sa,daemonsets,deployments,replicasets,statefulsets,cronjobs,jobs,ingresses,configmaps --all
    - kubectl delete namespace $KUBE_NAMESPACE

stop-k8s-dish-lmc-036:
  extends:
    - stop-k8s-dish-lmc-001
  variables:
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-dish-lmc-036"
    DISH_HELM_RELEASE: "4.1.0"
    K8S_DISH_LMC_CHART: "ska-dish-lmc"

stop-k8s-dish-lmc-063:
  extends:
    - stop-k8s-dish-lmc-001
  variables:
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-dish-lmc-063"
    DISH_HELM_RELEASE: "4.1.0"
    K8S_DISH_LMC_CHART: "ska-dish-lmc"

stop-k8s-dish-lmc-100:
  extends:
    - stop-k8s-dish-lmc-001
  variables:
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-dish-lmc-100"
    DISH_HELM_RELEASE: "4.1.0"
    K8S_DISH_LMC_CHART: "ska-dish-lmc"
